[project]
name = "good-products-deal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.33",
    "pyarrow>=23.0.0",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
]
